# CONFIGURAÇÕES GERAIS DA APLICAÇÃO
# ==========================================

# Define o nome interno da aplicação dentro do ecossistema do Spring Boot.
spring.application.name=controletarefas


# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS (PERSISTÊNCIA)


# URL de Conexão (JDBC): Indica o endereço onde o banco de dados está rodando.
# "localhost:5432" é a porta padrão do servidor na sua máquina.
# "/postgres" é o nome do banco de dados específico onde as tabelas serão criadas.
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# Usuário administrador do PostgreSQL.
spring.datasource.username=postgres

# Senha de acesso ao PostgreSQL.
spring.datasource.password=postgres


# ==========================================
# CONFIGURAÇÕES DO ORM (HIBERNATE / JPA)


# A instrução "ddl-auto=update" é a mais importante do ORM neste projeto!
# Ela diz para o Spring Boot ler todas as classes marcadas com @Entity (Categoria, Tarefa, Prioridade)
# e, ao rodar o projeto, criar ou atualizar automaticamente as tabelas e colunas lá no PostgreSQL.
spring.jpa.hibernate.ddl-auto=update

# Quando ativado (true), faz com que o Spring imprima no terminal (console) do VS Code 
# todos os comandos SQL nativos (SELECT, INSERT, UPDATE, DELETE) que o Hibernate está gerando.
# É excelente para monitorar o que está acontecendo por baixo dos panos.
spring.jpa.show-sql=true

# Especifica o "Dialeto" do banco de dados.
# Isso garante que o Hibernate traduza os comandos Java exatamente para a sintaxe SQL 
# que o PostgreSQL entende, evitando erros de compatibilidade.
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect